# Generated by Django 5.0.2 on 2024-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='preview',
            field=models.ImageField(blank=True, upload_to='wines/', verbose_name='Превью'),
        ),
    ]
